# fly.toml app configuration file generated for tunnel-test on 2023-04-27T13:26:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tunnel-test"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"
processes = []

[build]

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
